language: python
python:
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION='>=1.4,<1.5'
  - DJANGO_VERSION='>=1.5,<1.6'
  - DJANGO_VERSION='>=1.6,<1.7'

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION='>=1.4,<1.5'

before_install:
  - sudo apt-get install libenchant-dev

install:
  - pip install -q Django$DJANGO_VERSION
  - pip install 'git+https://github.com/rfk/pyenchant.git'
  - python setup.py -q install

script: python setup.py test
